%
%     This file was autogenerated by make_gateways.pl v0.01 (Tue Sep  4 2012),
%                                 on Fri  7 Sep 2012 09:07:54 CST
%
%     Copyright 2012 Matthew Roughan <matthew.roughan.edu.au>
%     Copyright 2012 Eric Parsonage <eric.parsonage.edu.au>
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.
%
%     Routines included here are:
%          LinePickingAllProblems
%          LinePickingCDF
%          LinePickingCheckParameters
%          LinePickingMean
%          LinePickingNameLookup
%          LinePickingNumberOfProblems
%          LinePickingPDF
%          LinePickingPrintAllProblems
%          LinePickingProblemLookup
%          LinePickingSimDistances
%          LinePickingSimPoints
%          LinePickingSupport
%          LinePickingVar
%
